// AUTO-GENERATED by cruspy-gen — DO NOT EDIT
// Public include for pymergetic.cruspy.models.document.metadata.Metadata — forwards to __init___gen.hpp.
#pragma once

#include "__init___gen.hpp"  // IWYU pragma: export
