// AUTO-GENERATED by easybind-rust-module — do not edit

#[cxx::bridge(namespace = "pymergetic::cruspy::models::document::metadata")]
pub mod ffi {
    unsafe extern "C++" {
        include!("schema/validate.hpp");
        include!("models/document/metadata/mod.hpp");

        type Metadata;

        #[Self = "Metadata"]
        fn make(
            author: String,
            tags: i32,
        ) -> UniquePtr<Metadata>;
        fn validate(self: &Metadata) -> Result<()>;
    }
}

use pyo3::prelude::*;

use crate::core::FieldDescriptor;
use crate::model_runtime::{self, ModelSpec, ModuleSpec};
use crate::schema::FieldMetaEntry;
use crate::shm::{ShmArena, ShmHandle, ShmView};


pub const METADATA_TYPE_FQN: &str = "pymergetic::cruspy::models::document::metadata::Metadata";
pub const METADATA_SCHEMA_HASH: u64 = 1145017226261610918;

pub const TYPE_FQN: &str = METADATA_TYPE_FQN;
pub const SCHEMA_HASH: u64 = METADATA_SCHEMA_HASH;

const METADATA_FIELD_DESCRIPTORS: &[FieldDescriptor] = &[
    FieldDescriptor { name: "author", kind: crate::core::FieldKind::String, offset: 0, size: 8, description: "Author name", optional: false },
    FieldDescriptor { name: "tags", kind: crate::core::FieldKind::Int32, offset: 8, size: 4, description: "Tag count", optional: false },
];

const METADATA_FIELD_META: &[FieldMetaEntry] = &[
        ("author", "string", "Author name", false, &[("max_len", "64")]),
        ("tags", "int32", "Tag count", false, &[("min", "0")]),
];

const METADATA_MODEL_DESCRIPTION: &str = "Document metadata";

static METADATA_SPEC: ModelSpec = ModelSpec {
    name: "Metadata",
    fqn: METADATA_TYPE_FQN,
    schema_hash: METADATA_SCHEMA_HASH,
    slab_size: 16,
    description: METADATA_MODEL_DESCRIPTION,
    field_descriptors: METADATA_FIELD_DESCRIPTORS,
    field_meta: METADATA_FIELD_META,
    pydantic_index: 0,
};

#[pyfunction]
#[pyo3(signature = (author="", tags=0))]
fn validate_metadata(py: Python<'_>, author: &str, tags: i32) -> PyResult<()> {
    model_runtime::validate_via_cxx(py, || {
        let doc = ffi::Metadata::make(author.into(), tags);
        doc.as_ref()
            .ok_or_else(|| "make_metadata failed".to_string())?
            .validate()
            .map_err(|err| err.to_string())
    })
}

#[pyfunction]
fn write_metadata_to_shm(_py: Python<'_>, arena: Bound<'_, ShmArena>, model: Bound<'_, PyAny>) -> PyResult<ShmHandle> {
    model_runtime::write_model_to_shm(
        &arena,
        &model,
        model_runtime::ModelBinding {
            fqn: METADATA_TYPE_FQN,
            schema_hash: METADATA_SCHEMA_HASH,
            field_meta: METADATA_FIELD_META,
        },
    )
}

#[pyfunction]
fn view_metadata_shm(py: Python<'_>, arena: Bound<'_, ShmArena>, handle: Bound<'_, ShmHandle>) -> PyResult<ShmView> {
    model_runtime::view_model_from_shm(py, &arena, &handle, MODULE.python_module, &METADATA_SPEC)
}

#[pyfunction]
fn metadata_type_descriptor_py() -> PyResult<Py<PyAny>> {
    model_runtime::type_descriptor_py(&METADATA_SPEC)
}


static MODULE: ModuleSpec = ModuleSpec {
    python_module: "pymergetic.cruspy.models.document.metadata",
    short_name: "metadata",
    pydantic_source: include_str!("models.gen.py"),
    models: &[
    &METADATA_SPEC,
    ],
    primary: 0,
};

pub fn register_module(parent: &Bound<'_, PyModule>) -> PyResult<()> {
    model_runtime::register_module(parent, &MODULE, |module, _py| {
        module.add_function(wrap_pyfunction!(metadata_type_descriptor_py, module)?)?;
        module.add_function(wrap_pyfunction!(validate_metadata, module)?)?;
        module.add_function(wrap_pyfunction!(write_metadata_to_shm, module)?)?;
        module.add_function(wrap_pyfunction!(view_metadata_shm, module)?)?;
        module.add_function(wrap_pyfunction!(type_descriptor_py, module)?)?;
        Ok(())
    })
}

#[pyfunction]
fn type_descriptor_py() -> PyResult<Py<PyAny>> {
    model_runtime::type_descriptor_py(&MODULE.models[MODULE.primary])
}

