# // AUTO-GENERATED by easybind-rust-module — do not edit

def make_models():
    from pydantic import BaseModel, Field

    class Metadata(BaseModel):
        __doc__ = "Document metadata"
        author: str = Field(default="", max_length=64, description="Author name")
        tags: int = Field(default=0, ge=0, description="Tag count")

    return (Metadata,)
