# AUTO-GENERATED by cruspy-gen — DO NOT EDIT
"""Import model packages so hand-written ``CRUSPY_REGISTER_METHOD`` hooks run."""

from __future__ import annotations

import pymergetic.cruspy.models.document  # noqa: F401
import pymergetic.cruspy.models.document.metadata  # noqa: F401
import pymergetic.cruspy.models.hello  # noqa: F401
