#!/usr/bin/env python3
"""EP-0010 unified tree validator for cruspy."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

GENERATED_HEADER = "// AUTO-GENERATED by easybind-rust-module — do not edit"
PYI_HEADER = f"# {GENERATED_HEADER}"


def check_tree(root: Path) -> list[str]:
    failures: list[str] = []
    src = root / "src" / "pymergetic" / "cruspy"

    if not src.is_dir():
        failures.append(f"missing source tree: {src}")
        return failures

    for path in src.rglob("*"):
        if not path.is_file():
            continue
        if path.name.endswith(".gen.py") or path.suffix == ".pyi":
            expected = PYI_HEADER
        elif path.name.endswith(".gen.rs"):
            expected = GENERATED_HEADER
        else:
            continue
        text = path.read_text(encoding="utf-8")
        if not text.startswith(expected):
            failures.append(f"generated file missing header: {path}")

    manifest = src / "manifest.json"
    if not manifest.is_file():
        failures.append("missing src/pymergetic/cruspy/manifest.json")
        return failures

    payload = json.loads(manifest.read_text(encoding="utf-8"))
    for model in payload.get("models", []):
        source = Path(model["source"])
        if not source.is_file():
            failures.append(f"manifest model source missing: {source}")
        cpp = root / model["cpp"]
        if not cpp.is_file():
            failures.append(f"manifest model cpp missing: {cpp}")
        bridge_rs = root / model["bridge_rs"]
        if not bridge_rs.is_file():
            failures.append(f"manifest bridge missing: {bridge_rs}")

    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="cruspy package root",
    )
    args = parser.parse_args()
    failures = check_tree(args.root)
    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1
    print(f"unified tree check passed for {args.root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
