#!/usr/bin/env python3
"""EP-0010 unified tree validator for cruspy."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

GENERATED_HEADER = "// AUTO-GENERATED by easybind-rust-module — do not edit"
PYI_HEADER = f"# {GENERATED_HEADER}"


def check_tree(root: Path) -> list[str]:
    failures: list[str] = []
    src = root / "src" / "pymergetic" / "cruspy"
    generated = root / "generated"

    if not src.is_dir():
        failures.append(f"missing source tree: {src}")
        return failures

    for path in generated.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix not in {".rs", ".pyi"}:
            continue
        text = path.read_text(encoding="utf-8")
        expected = PYI_HEADER if path.suffix == ".pyi" else GENERATED_HEADER
        if not text.startswith(expected):
            failures.append(f"generated file missing header: {path}")

    manifest = generated / "manifest.json"
    if not manifest.is_file():
        failures.append("missing generated/manifest.json")

    for model_dir in (src / "models").glob("*"):
        if not model_dir.is_dir():
            continue
        if not (model_dir / "types.hpp").is_file() and not (model_dir / "mod.hpp").is_file():
            failures.append(f"model directory missing header: {model_dir}")

    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="cruspy package root",
    )
    args = parser.parse_args()
    failures = check_tree(args.root)
    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1
    print(f"unified tree check passed for {args.root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
