"""PyO3 runtime surface (implemented in ``pymergetic.cruspy._native``)."""

from collections.abc import Callable
from typing import Any, ClassVar, Self, TypeVar

_T = TypeVar("_T")

class MemoryHandle:
    @property
    def schema_hash(self) -> int: ...
    @property
    def byte_size(self) -> int: ...
    def type_fqn(self) -> str: ...
    def field_i32(self, name: str) -> int: ...
    def set_field_i32(self, name: str, value: int) -> None: ...
    def field_i64(self, name: str) -> int: ...
    def set_field_i64(self, name: str, value: int) -> None: ...
    def field_f64(self, name: str) -> float: ...
    def set_field_f64(self, name: str, value: float) -> None: ...
    def field_bool(self, name: str) -> bool: ...
    def set_field_bool(self, name: str, value: bool) -> None: ...
    def field_string(self, name: str) -> str: ...
    def set_field_string(self, name: str, value: str) -> None: ...
    def field_object(self, name: str) -> MemoryHandle: ...
    def call_bool(self, method: str) -> bool: ...
    def call_void(self, method: str) -> None: ...
    def call_f64(self, method: str, arg0: str | None = None, arg1: str | None = None) -> float: ...
    def call_bytes(self, method: str) -> bytes: ...
    @classmethod
    def _call_constructor(cls, fqn: str, method: str, arg0: str, arg1: str) -> Self: ...
    @staticmethod
    def _call_static_str(fqn: str, method: str) -> str: ...

def bootstrap() -> None: ...
def domain_stats_json() -> str: ...
def create(fqn: str, domain: str | None = None) -> MemoryHandle: ...
def describe(fqn: str) -> str: ...
def method_impl(model_class: type[_T], method_name: str, func: Callable[..., Any]) -> None: ...
