// AUTO-GENERATED by easybind-rust-module — do not edit

#[cxx::bridge(namespace = "pymergetic::cruspy::models::document")]
pub mod ffi {
    unsafe extern "C++" {
        include!("schema/validate.hpp");
        include!("models/document/mod.hpp");

        type Document;

        #[Self = "Document"]
        fn make(
            id: i32,
            text: String,
            score: f64,
            active: bool,
            has_revision: bool,
            revision: i32,
            meta_author: String,
            meta_tags: i32,
        ) -> UniquePtr<Document>;
        fn validate(self: &Document) -> Result<()>;
    }
}

use pyo3::prelude::*;

use crate::core::FieldDescriptor;
use crate::model_runtime::{self, ModelSpec, ModuleSpec};
use crate::schema::FieldMetaEntry;
use crate::shm::{ShmArena, ShmHandle, ShmView};


pub const DOCUMENT_TYPE_FQN: &str = "pymergetic::cruspy::models::document::Document";
pub const DOCUMENT_SCHEMA_HASH: u64 = 14874371387292292213;

pub const TYPE_FQN: &str = DOCUMENT_TYPE_FQN;
pub const SCHEMA_HASH: u64 = DOCUMENT_SCHEMA_HASH;

const DOCUMENT_FIELD_DESCRIPTORS: &[FieldDescriptor] = &[
    FieldDescriptor { name: "id", kind: crate::core::FieldKind::Int32, offset: 0, size: 4, description: "Primary key", optional: false },
    FieldDescriptor { name: "text", kind: crate::core::FieldKind::String, offset: 8, size: 8, description: "Body text", optional: false },
    FieldDescriptor { name: "score", kind: crate::core::FieldKind::Float64, offset: 16, size: 8, description: "Relevance score", optional: false },
    FieldDescriptor { name: "active", kind: crate::core::FieldKind::Bool, offset: 24, size: 1, description: "Whether the document is active", optional: false },
    FieldDescriptor { name: "revision", kind: crate::core::FieldKind::Int32, offset: 32, size: 4, description: "Content revision, if known", optional: true },
    FieldDescriptor { name: "meta", kind: crate::core::FieldKind::Model, offset: 40, size: 8, description: "Document metadata", optional: false },
];

const DOCUMENT_FIELD_META: &[FieldMetaEntry] = &[
        ("id", "int32", "Primary key", false, &[("min", "1")]),
        ("text", "string", "Body text", false, &[("max_len", "512")]),
        ("score", "float64", "Relevance score", false, &[("ge", "0.0"), ("le", "1.0")]),
        ("active", "bool", "Whether the document is active", false, &[]),
        ("revision", "optional_int32", "Content revision, if known", true, &[("min", "0")]),
        ("meta", "model:pymergetic::cruspy::models::document::metadata::Metadata", "Document metadata", false, &[]),
];

const DOCUMENT_MODEL_DESCRIPTION: &str = "Indexed text document";

static DOCUMENT_SPEC: ModelSpec = ModelSpec {
    name: "Document",
    fqn: DOCUMENT_TYPE_FQN,
    schema_hash: DOCUMENT_SCHEMA_HASH,
    slab_size: 48,
    description: DOCUMENT_MODEL_DESCRIPTION,
    field_descriptors: DOCUMENT_FIELD_DESCRIPTORS,
    field_meta: DOCUMENT_FIELD_META,
    pydantic_index: 0,
};

#[pyfunction]
#[pyo3(signature = (id=0, text="", score=0.0, active=false, revision=None, meta_author="", meta_tags=0))]
fn validate_document(py: Python<'_>, id: i32, text: &str, score: f64, active: bool, revision: Option<i32>, meta_author: &str, meta_tags: i32) -> PyResult<()> {
    model_runtime::validate_via_cxx(py, || {
        let doc = ffi::Document::make(id, text.into(), score, active, revision.is_some(), revision.unwrap_or(0), meta_author.into(), meta_tags);
        doc.as_ref()
            .ok_or_else(|| "make_document failed".to_string())?
            .validate()
            .map_err(|err| err.to_string())
    })
}

#[pyfunction]
fn write_document_to_shm(_py: Python<'_>, arena: Bound<'_, ShmArena>, model: Bound<'_, PyAny>) -> PyResult<ShmHandle> {
    model_runtime::write_model_to_shm(
        &arena,
        &model,
        model_runtime::ModelBinding {
            fqn: DOCUMENT_TYPE_FQN,
            schema_hash: DOCUMENT_SCHEMA_HASH,
            field_meta: DOCUMENT_FIELD_META,
        },
    )
}

#[pyfunction]
fn view_document_shm(py: Python<'_>, arena: Bound<'_, ShmArena>, handle: Bound<'_, ShmHandle>) -> PyResult<ShmView> {
    model_runtime::view_model_from_shm(py, &arena, &handle, MODULE.python_module, &DOCUMENT_SPEC)
}

#[pyfunction]
fn document_type_descriptor_py() -> PyResult<Py<PyAny>> {
    model_runtime::type_descriptor_py(&DOCUMENT_SPEC)
}


static MODULE: ModuleSpec = ModuleSpec {
    python_module: "pymergetic.cruspy.models.document",
    short_name: "document",
    pydantic_source: include_str!("models.gen.py"),
    models: &[
    &DOCUMENT_SPEC,
    ],
    primary: 0,
};

pub fn register_module(parent: &Bound<'_, PyModule>) -> PyResult<()> {
    model_runtime::register_module(parent, &MODULE, |module, _py| {
        module.add_function(wrap_pyfunction!(document_type_descriptor_py, module)?)?;
        module.add_function(wrap_pyfunction!(validate_document, module)?)?;
        module.add_function(wrap_pyfunction!(write_document_to_shm, module)?)?;
        module.add_function(wrap_pyfunction!(view_document_shm, module)?)?;
        module.add_function(wrap_pyfunction!(type_descriptor_py, module)?)?;
        Ok(())
    })
}

#[pyfunction]
fn type_descriptor_py() -> PyResult<Py<PyAny>> {
    model_runtime::type_descriptor_py(&MODULE.models[MODULE.primary])
}


#[path = "metadata/mod.gen.rs"]
pub mod metadata;
