# // AUTO-GENERATED by easybind-rust-module — do not edit

def make_models():
    from pydantic import BaseModel, Field

    from pymergetic.cruspy.models.document.metadata import Metadata

    class Document(BaseModel):
        __doc__ = "Indexed text document"
        id: int = Field(ge=1, description="Primary key")
        text: str = Field(default="", max_length=512, description="Body text")
        score: float = Field(ge=0.0, le=1.0, description="Relevance score")
        active: bool = False
        revision: int | None = Field(default=None, ge=0, description="Content revision, if known")
        meta: Metadata = Field(default_factory=Metadata, description="Document metadata")

    return (Document,)
